# Site settings
title: Hiromu Tsuruta
description: 'Business Card Page'
url: 'https://crane-hiromu.github.io'
baseurl: ''
profilepic: '/images/HiromuTsuruta.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Hiromu Tsuruta'
  email: h.crane.t@gmail.com
  twitter_username: hcrane14
  github_username:  crane-hiromu
  linkedin_username:  hiromu-t-940107187

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png'] # todo
